config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  get  "/admin",     to: "sessions#new"
  post "/admin",     to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  get "/about",      to: "about#index"
  get "/store",      to: "items#index"

  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]

  post "/cart_items", to: "cart_items#create"
  get "/cart",        to: "cart_items#index"
  delete '/cart_items', to: "cart_items#destroy"
  put '/cart_items', to: "cart_items#update"

  resources :charges
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

  validates :username, :password, presence: true
end

app/models/cart.rb
class Cart
  attr_reader :data

  def initialize(input_data = {})
    @data = input_data || Hash.new
  end

  def items
    @data.map do |item_id, quantity|
      item = Item.find(item_id)
      CartItem.new(item, quantity)
    end
  end

  def add_item(item)
    data[item.id.to_s] ||= 0
    data[item.id.to_s] += 1
  end

  def remove_item(item_id)
    data.delete(item_id.to_s)
  end

  def update_item(item_id, quantity)
    data[item_id.to_s] = quantity.to_i
  end

  def total
    prices = items.map do |i|
      i.price * i.quantity
    end

    prices.reduce(:+)
  end
end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :quantity, :item

  def initialize(item, quantity=0)
    super(item)
    @quantity = quantity
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category

  has_attached_file :item_image, styles: { large: "800x800>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :item_image, content_type: /\Aimage\/.*\Z/

  validates :title, :description, :price, :category_id, :item_image, presence: true
  validates :price, numericality: { only_integer: true }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize!

  def show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_admin

  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id]) if session[:admin_id]
  end

  def authorize!
    redirect_to root_path unless current_admin
  end

  def cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    cart.add_item(@item)
    session[:cart] = cart.data
    redirect_to store_path
  end

  def index
    @cart_items = cart.items
    @subtotal = cart.total
    session[:subtotal] = @subtotal
  end

  def destroy
    @item = Item.find(params[:item_id])
    cart.remove_item(@item.id)
    redirect_to cart_path
    flash[:notice] = "Item removed from cart"
  end

  def update
    @item = Item.find(params[:item_id])
    cart.update_item(@item.id, params[:quantity])
    redirect_to cart_path
    flash[:notice] = "Your cart has been updated"
    count
  end

  def count
    cart.data.keys.count
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = session[:subtotal]
  end

  def create
    # Amount in cents
    @amount = session[:subtotal] * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authorize!, only: [ :new, :create ]

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find_by(id: params[:id])
  end

  def update
    @item = Item.find_by(id: params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find_by(id: params[:id])
    @item.destroy
    redirect_to store_path
  end

  private

    def item_params
      params.require(:item).permit(:title, :description, :price, :category_id,
                                   :item_image)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @admin = Admin.find_by(username: params[:session][:username])
      if @admin && @admin.authenticate(params[:session][:password])
        session[:admin_id] = @admin.id
        redirect_to root_path
      else
        render :new
      end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
  <div class="row">

    <div class="col s3 about-left-image">
      <%= image_tag "sun-rose-graduation-about-page.jpg", class: "about-image" %>
    </div>

    <div class="col s6">
      <div class="card">
        <div class="card-content white-text">

          <p>+<span class="about-highlights">Warrior Status</span>+ is a fashion concept, trademark business focused on empowering Native youth,
            cultural sustainability and making Indigenous Global connections.
            A unique company marketing fashion and art works of Lakota designer Sun Rose Iron Shell.
            As a company we provide a specific genre of art that frames a life style based on Indigenous concepts of living
            as a warrior. Our mission is to uplift Indigenous youth by embracing cultural values to enlighten future generations</span>.
            We represent a new generation of intellectuals, leaders and most of all warriors.
            We challenge the warriors of the globe to stand and reclaim their status.
            We promote cultural sustainability and telling the truth about our histories<span class="about-highlights">.</span>
          </p>

          <br>

          <p>Designed exclusively by <span class="about-highlights">Sun Rose Iron Shell</span>,
            a graduate of the highly acclaimed Institute of American Indian Arts (IAIA).
            Sun Rose received her Bachelors of Fine Arts and Bachelors in Museum studies in 2012,
            where she also launched as a fashion designer at the Museum of Contemporary Native Arts.
            Sun Rose is Sicangu and Oglala, Lakota, raised in an academic setting surrounded by activism.
            Her work explores Lakota ideologies and the use of supernatural icons throughout Indigenous oral histories.
            Sun Rose’s design style is a direct influence of Northern Plains classical arts,
            such as, Parfleche, quill work (wo’skapi), dress design and hide paintings.
            Her enthusiasm for abstract design radiates from Great Plains style geometric design.
            Sun Rose uses the icon of woman, to reclaim Indigenous feminine identity and image.
            Also to bring awareness to the negative stereotypes that keep the number of missing and murdered Indigenous woman growing and growing. Sun Rose is best known for her hand painted,
            Parfleche inspired earrings and accessories<span class="about-highlights">.</span>
          </p>

        </div>
      </div>
    </div>


    <div class="col s3 about-right-image">
      <%= image_tag "sun-rose-about-page.jpg", class: "about-image" %>
    </div>

  </div>

app/views/admin/show.html.erb
<div class="container">
  Admin Dashboard
</div>

app/views/cart_items/index.html.erb
<div class="container">

<h3>Cart</h3>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

  <div class="row">
    <div class="col s12">

      <table>

        <thead>
          <tr id="cart-table-headings">
              <th data-field="title">Title</th>
              <th data-field="price">Price</th>
              <th data-field="quantity">Quantity</th>
              <th data-field="update"></th>
              <th></th>
          </tr>
        </thead>

        <% @cart_items.each do |i| %>
        <tbody>
          <tr id="cart-item-info">
            <td class="title"> <%= i.title %></td>
            <td class="price">$ <%= i.price %> </td>
            <td id="quantity-box">
              <%= form_tag cart_items_path, method: :put do %>
              <%= hidden_field_tag :item_id, i.id %>
              <%= number_field_tag 'quantity', i.quantity, within: 1...10 %>
              <%= submit_tag "Update", class: "waves-effect waves-teal btn" %>
            </td>
            <td>
            </td>
              <% end %>
            <td class="Remove"><%= link_to "Remove", cart_items_path(item_id: i.id), method: :delete%></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col s6">
      Total: <%= number_to_currency @subtotal %>
    </div>
    <div class="col s6">
      <%= link_to "Checkout", new_charge_path, class: "btn" %>
    </div>
  </div>

</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= number_to_currency(@amount / 100) %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= number_to_currency @amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= @amount * 100 %>
          data-locale="auto"></script>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <%= render "shared/error_messages", object: @item %>

  <div class="row">
    <div class="col s12">
      <h4 id="add-item-title">Edit Item Below</h4>
    </div>
  </div>

  <%= form_for @item, multipart: true do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label      :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.label      :description %>
      <%= f.text_area  :description, class: "materialize-textarea" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.label      :price %>
      <%= f.text_field :price %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.collection_select :category_id, Category.all, :id, :name %>
      <%= f.label             :category %>
    </div>
  </div>

  <div class="row">
    <div class="file-field input-field col s12">
      <div class="btn">
        <span>Upload Image</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <%= f.file_field :item_image %>
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="input-field col s2">
      <%= f.submit "Update", class: "waves-effect waves-light btn black" %>
    </div>
  <% end %>

    <div class="input-field col s2">
      <%= link_to "Cancel",
          item_path(@item), class: "waves-effect waves-light btn black" %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">

<% if current_admin %>
  <div class="row">

    <div class="col s3 offset-s10">
      <%= link_to "Add Item", new_item_path, class: "waves-effect waves-light btn black" %>
    </div>
  </div>
<% end %>
</div>

  <div class="row">
    <% Category.all.each do |category| %>
    <div class="category-container col s10 offset-s2" id='<%="#{category.name}"%>-container'>

      <h3 class="category-titles">
        <%= category.name %>
      </h3>

      <% category.items.map do |item| %>
      <div class="col s3 item-info">
        <%= image_tag item.item_image(:medium), class: "item-images" %>
        <h6 class="item-titles"><%= link_to item.title, item_path(item) %></h6>
        <p><%= truncate(item.description, :length => 140) %></p>
        <p><%= number_to_currency item.price %></p>
      </div>
      <% end %>
      <br>
    </div>
    <% end %>
  </div>

app/views/items/new.html.erb
<div class="container">
  <%= render "shared/error_messages", object: @item %>

  <div class="row">
    <div class="col s12">
      <h4 id="add-item-title">Add A New Item Below</h4>
    </div>
  </div>

  <%= form_for @item, multipart: true do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label      :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.label      :description %>
      <%= f.text_area  :description, class: "materialize-textarea" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.label      :price %>
      <%= f.text_field :price %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.collection_select :category_id, Category.all, :id, :name %>
      <%= f.label             :category %>
    </div>
  </div>

  <div class="row">
    <div class="file-field input-field col s12">
      <div class="btn">
        <span>Upload Image</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <%= f.file_field :item_image %>
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s2">
      <%= f.submit "Add Item", class: "waves-effect waves-light btn black" %>
    </div>
  <% end %>
    <div class="input-field col s2">
      <%= link_to "Cancel",
                  store_path, class: "waves-effect waves-light btn black" %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<% if current_admin %>
  <div class="row">

    <div class="col s3 offset-s8">
      <%= link_to "Edit Item", edit_item_path(@item), class: "waves-effect waves-light btn black" %>
      <%= link_to "Delete Item", item_path(@item), method: :delete, class: "waves-effect waves-light btn black" %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col s2 offset-s1 item-info-box">
    <h4 id="item-title"><%= @item.title %></h4>
    <p>Description: <%= @item.description %></p>
    <p>Price: <%= number_to_currency @item.price %></p>
    <p>Category: <%= @item.category.name %></p>
    <%= button_to "Add to cart", cart_items_path(item_id: @item.id), class: "waves-effect waves-teal btn" %>
  </div>
  <div class="col s9 large-item-image"><%= image_tag @item.item_image(:large) %></div>
</div>

app/views/layouts/_control_panel.html.erb
<ul id="slide-out" class="side-nav">
  <li><a href="#!">Edit Profile</a></li>
  <li> <%= link_to "Logout", logout_path, method: :delete  %> </li>
</ul>
<a href="#" data-activates="slide-out" class="button-collapse show-on-large">
  <i class="mdi-navigation-menu"></i></a>

app/views/layouts/_navbar.html.erb
<nav class="top-nav">
  <div class="nav-wrapper">
    <%= link_to "Warrior Status", root_path, class: "brand-logo center" %>
    <a href="#" data-activates="mobile-nav" class="button-collapse">
      <i class="material-icons">menu</i></a>

    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Store", store_path %></li>
      <li><%= link_to "Cart", cart_path %></li>
    </ul>

    <%= render partial: "layouts/sidenav" %>

  </div>
</nav>

app/views/layouts/_sidenav.html.erb
<ul id="mobile-nav" class="side-nav">

<% if current_admin %>
  <li><%= link_to "Logout", logout_path, method: :delete  %> </li>
<% end %>
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Store", store_path %></li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>+Warrior Status+</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= render partial: "layouts/navbar" %>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/main/index.html.erb
<div class="container">

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p>-<%= message %></p>
  <% end %>
<% end %>